### ISSUE TITLE
Provide an option for the target resource group name

### ISSUE THREAD

**Issue by roberto-mardeni** [Azure/Azure-Websites-Migration-Tool#20]
The tool generates a fixed name for the target resource group as **Server-Migration-{region}** which is not ideal for most enterprise customers. The tool should allow to select an existing resource group, enter a custom resource group name or default to the **Server-Migration-{region}** name.

**Comment by Grigor88451201** [comment]
R

**Comment by fashaikh** [comment]
related to https://github.com/Azure/Azure-Websites-Migration-Tool/issues/7

**Comment by fashaikh** [comment]
The chnage is live. Thanks for your feedback!
