### ISSUE TITLE
Provide a way to export readiness assessment results

### ISSUE THREAD

**Issue by dsukoneck** [Azure/Azure-Websites-Migration-Tool#22]
Having to view and analyze readiness assessment results within the app is migration assistant tool (or website) doesn't scale when large numbers of services are assessed. Need to analyze larger results data sets by exporting to csv, html, json, etc.

**Comment by fashaikh** [comment]
Did you try exporting using this button. let me know if you need a different option..

![image](https://user-images.githubusercontent.com/2650941/47249998-10019e80-d3d0-11e8-9616-1eae8aedd01a.png)

**Comment by dsukoneck** [comment]
@fashaikh that works great, hadn't explored that file (duh!) appreciate you calling that out.
