### ISSUE TITLE
Error when trying to install 

### ISSUE THREAD

**Issue by mullermand** [Azure/Azure-Websites-Migration-Tool#23]
When i try to install the app, on a Server 2008, i get this error: 
Unable to install or run the application. The application requires that assembly
Microsoft.Management.Infastructure Version 1.0.0.0
be installed in the Global Assembly Cache (GAC) first.

Any ideeas ?

**Comment by fashaikh** [comment]
Could you try using the offline package from here  https://movemetothecloud.net/WindowsMigration ? The bundle contains additional dependencies, including Microsoft.Management.Infastructure Version 1.0.0.0

**Comment by fashaikh** [comment]
Closing tentatively. please reopen if the offline package didnt help.

**Comment by jrojas02** [comment]
Same behaivor using offline package.
OS version = Win2008R2 Standard 64bits
Is there an online azure site migration tool? If so, I could be a better shot.

@Jhonatan
