### ISSUE TITLE
Cached Migration Readiness ID?

### ISSUE THREAD

**Issue by kapntech** [Azure/Azure-Websites-Migration-Tool#26]
Trying to run a remote assessment. When I export locally the report is for the correct server but when I upload it returns results from another server?

**Comment by fashaikh** [comment]
Sorry about the delay in response. Could you provide the reportid ? I can try reseting  the id so it if there is a cache it'll go away.
Just curious, did you happen to do assement of sites one another server at any point from this machine. the readiness id is unique to each machine
