### ISSUE TITLE
Tool doesn't allow you to select existing Azure profiles

### ISSUE THREAD

**Issue by timheuer** [Azure/Azure-Websites-Migration-Tool#6]
If you've already configured an App Service Plan you aren't able to select it using the tool.  This creates problems when you get an error during migration and have to start over.  You end up creating multiple App Service Plans...bad customer experience.

**Comment by fashaikh** [comment]
The last set of changes should have strengthened the cases where some existing app service plans in the region do not populate. 
You should also try to specify the correct resource group in the previous screen and see if it helps

![image](https://user-images.githubusercontent.com/2650941/58144037-bbdac900-7c01-11e9-8eca-0b3db4cb2f37.png)
