### ISSUE TITLE
Migration tool did migrate content or database

### ISSUE THREAD

**Issue by Phydeauxman** [Azure/Azure-Websites-Migration-Tool#7]
I tried to use the tool to migrate a web site that is running on a Windows Server 2012 R2 server pointing to a database that is on a separate Windows Server 2012 R2 server running SQL 2014.  The only thing the tool did was create a new App Service and new App Service Plan.  It did not migrate any of the content nor did it even try to do anything with the database.  I ran the tool from the web server.  One other shortcoming of the app was that it did not give me an option to use an existing Resource Group or to even create a new one with the name I want...it just creates its own Resource Group with the name it wants.

**Comment by fashaikh** [comment]
This is already fixed. Also checkout our new tool at https://appmigration.microsoft.com which is tailored for hybrid connections
